export const SAVE_HOT_TOPICS = 'SAVE_HOT_TOPICS';
export const SAVE_WELCOME_MESSAGES = 'SAVE_WELCOME_MESSAGES';
export const SAVE_COURSES = 'SAVE_COURSES';
export const SAVE_COURSE_CATEGORIES = 'SAVE_COURSECATEGORIES';
export const SAVE_TOPICS = 'SAVE_TOPICS';
export const SAVE_FORUMS = 'SAVE_FORUMS';
export const SAVE_COURSE_INCLUDES = 'SAVE_COURSE_INCLUDES';
